### ISSUE TITLE
密码加密方式

### ISSUE THREAD

**Issue by Steve0x2a** [azxj/jnu-stu-health-report#1]
根据简单的研究, 登录请求对密码的加密是使用AES的CBC模式进行加密, 及使用PKCS7进行填充.
迫于对Go理解不深, 只能贴上Python代码
```python3
def pkcs7padding(text):
    """
    明文使用PKCS7填充
    """
    bs = 16
    length = len(text)
    bytes_length = len(text.encode('utf-8'))
    padding_size = length if (bytes_length == length) else bytes_length
    padding = bs - padding_size % bs
    padding_text = chr(padding) * padding
    return text + padding_text

def aes_encrypt(content):
    CRYPTOJSKEY = 'xAt9Ye&SouxCJziN'
    key = CRYPTOJSKEY.encode('utf-8')
    cryptor = AES.new(key,AES.MODE_CBC,key)
    return base64.b64encode(cryptor.encrypt(pkcs7padding(content))).decode().replace('/','_').replace('+','-').replace('=','*',1)

```

**Comment by azxj** [comment]
> 根据简单的研究, 登录请求对密码的加密是使用AES的CBC模式进行加密, 及使用PKCS7进行填充.
> 迫于对Go理解不深, 只能贴上Python代码
> 
> ```python
> def pkcs7padding(text):
>     """
>     明文使用PKCS7填充
>     """
>     bs = 16
>     length = len(text)
>     bytes_length = len(text.encode('utf-8'))
>     padding_size = length if (bytes_length == length) else bytes_length
>     padding = bs - padding_size % bs
>     padding_text = chr(padding) * padding
>     return text + padding_text
> 
> def aes_encrypt(content):
>     CRYPTOJSKEY = 'xAt9Ye&SouxCJziN'
>     key = CRYPTOJSKEY.encode('utf-8')
>     cryptor = AES.new(key,AES.MODE_CBC,key)
>     return base64.b64encode(cryptor.encrypt(pkcs7padding(content))).decode().replace('/','_').replace('+','-').replace('=','*',1)
> ```

🙏 非常感谢！加密的步骤已经加到脚本中
